### ISSUE TITLE
audite command not working

### ISSUE THREAD

**Issue by Hoss3770** [georgi/audite#17]
```
audite test.mp3
```

Outputs : 

```
/usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- curses (LoadError)
    from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/lib/ruby/gems/2.3.0/gems/audite-0.4.0/bin/audite:3:in `<top (required)>'
    from /usr/local/bin/audite:23:in `load'
    from /usr/local/bin/audite:23:in `<main>'
```

**Comment by ElMagic1980** [comment]
The command "gem install curses" should fix it
