### ISSUE TITLE
Exit not handled gracefully

### ISSUE THREAD

**Issue by vipulnsward** [georgi/audite#2]
I am on Mac OSX, with ruby- 1.9.3-p125

Playing a sample song works good, but on reaching end of mp3 I get following 
# 

`
playing sample.mp3    389 seconds of 390 total
###### 

Note: Illegal Audio-MPEG-Header 0x00000000 at offset 6222168.
                                                             Note: Trying to resync...
                                                                                      Note: Skipped 1024 bytes in input.
                                                                                                                        [parse.c:1159] error: Giving up resync after 1024 bytes - your stream is not nice... (maybe increasing resync limit could help).
                                               A generic mpg123 error.
                                                                      /Users/sward/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/audite-0.1.5/lib/audite.rb:101:in `read'
                                                                                                                                                                               /Users/sward/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/audite-0.1.5/lib/audite.rb:101:in`read'
                                                                               /Users/sward/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/audite-0.1.5/lib/audite.rb:43:in `process'
                                                                                                                                                                                          /Users/sward/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/audite-0.1.5/lib/audite.rb:32:in`block (2 levels) in start_thread'
                                                                                                                     /Users/sward/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/audite-0.1.5/lib/audite.rb:31:in `loop'
                    /Users/sward/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/audite-0.1.5/lib/audite.rb:31:in`block in start_thread'
# `

**Comment by icetimux** [comment]
Same issue here, have you found a fix @vipulnsward ?
